version: "3"
services:
  postgres:
    environment:
      - POSTGRES_DB=refigeratorservicedb
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app_password
    image: postgres:9.6.17
    ports:
      - "5432:5432"
  tests:
    image: gradle:6.3.0-jdk14
    volumes:
      - .:/home/gradle/project
    links:
      - postgres
    depends_on:
      - postgres
    working_dir: "/home/gradle/project"
    command: "gradle test"
    privileged: true
